### ISSUE TITLE
Lights starts to blink with no motivation

### ISSUE THREAD

**Issue by xion87** [rsm-imap-cc/alienware-kbl#5]
I noticed after some reboots, lights start to blink regularity for 5 second and with 10 second interval...  for example i setted it as light green, i found it the keyboard was dark green and touchpad not lighted and started to blink.... going to panel and setting light green one part of light, it fixed it (light green and no  more blink)...

**Comment by rsm-imap-cc** [comment]
Thanks for confirming this bug, I've also noticed that some times weird stuff happens. Some times when I start the computer all the lights are blinking, so I don't think that it be your computer or the fact that it is an M17xR3.

For the moment I consider it as a minor bug because it only affects one of many restarts and by setting a configuration the bug seems to be momentary fixed. But Anyways for the next release I've written an simple daemon, and when booting the computer it will turn on or off the lights, so by doing this the bug will not be visible even if it stills there.

**Comment by rsm-imap-cc** [comment]
Closed with alienware-kbl >= 1.4.0~0
