### ISSUE TITLE
Not really a issue...

### ISSUE THREAD

**Issue by xion87** [rsm-imap-cc/alienware-kbl#7]
Where and how i can install libgtk-3-0 (>=3.12) for use the latest version of alienware-kbl? i cant find it.. :(

**Comment by rsm-imap-cc** [comment]
What distribution are you using? normally it should be installed, the package name is libgtk-3-0

**Comment by xion87** [comment]
I am using linux mint, yeah it say libgtk-3-0 is already installed but not the >=3.12 version so i can't install it

**Comment by rsm-imap-cc** [comment]
Oh this is weird, I just checked and Mint has  libgtk-3-0  normally has the version 3.14, could you please check that? I'll make the fix

**Comment by rsm-imap-cc** [comment]
Which linux mint version are you using?

**Comment by xion87** [comment]
17.1 codename "Rebecca"

**Comment by rsm-imap-cc** [comment]
It seems that Linux mint made a weird downgrade of GTK.  While betsy ( a previous version ) had  3.14, the new
stable version of min has 3.10.8~8

I may sujest installing 3.12 from [the linux mint repository](http://packages.linuxmint.com/search.php?keyword=libgtk-3-0&release=any&section=any)

This is strange because Ubuntu is using 3.14 and Debian 3.12.

If you have problems installing it let me know :)

**Comment by xion87** [comment]
okey i will try when i go to home, and let you know if all it working :)

**Comment by rsm-imap-cc** [comment]
I took a look, and actually it will be a hell to install libgtk-3-0 > 12 because you will need to intall like 5 ot 6 dependences ( at least ).  The good news is that I think that  the version 10 actually works fine for the program, so I'll downgrade the package dependence. I'm gona do this as soon as I can. If you want to try it your self you can install the tar.gz package and say "yes" to the dependences

**Comment by xion87** [comment]
i tryed to install that package it say that is already installed lol....

**Comment by rsm-imap-cc** [comment]
I've made the downgrade, and it is now working over Mint. The only problem is that it seems that systemd is not yet on mint. I made a comment about that: https://github.com/rsm-imap-cc/alienware-kbl/issues/8

This is now closed. Thanks for helping! it is hard to me to test/maintain multiple distros
